// default package
// Generated 19.Aðu.2013 17:08:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Musteriler generated by hbm2java
 */
public class Musteriler implements java.io.Serializable {

	private Integer musteriId;
	private String ad;
	private String soyad;
	private Integer yas;
	private Integer cinsiyetId;
	private Set sonuclars = new HashSet(0);

	public Musteriler() {
	}

	public Musteriler(String ad, String soyad, Integer yas, Integer cinsiyetId,
			Set sonuclars) {
		this.ad = ad;
		this.soyad = soyad;
		this.yas = yas;
		this.cinsiyetId = cinsiyetId;
		this.sonuclars = sonuclars;
	}

	public Integer getMusteriId() {
		return this.musteriId;
	}

	public void setMusteriId(Integer musteriId) {
		this.musteriId = musteriId;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public String getSoyad() {
		return this.soyad;
	}

	public void setSoyad(String soyad) {
		this.soyad = soyad;
	}

	public Integer getYas() {
		return this.yas;
	}

	public void setYas(Integer yas) {
		this.yas = yas;
	}

	public Integer getCinsiyetId() {
		return this.cinsiyetId;
	}

	public void setCinsiyetId(Integer cinsiyetId) {
		this.cinsiyetId = cinsiyetId;
	}

	public Set getSonuclars() {
		return this.sonuclars;
	}

	public void setSonuclars(Set sonuclars) {
		this.sonuclars = sonuclars;
	}

}
