// default package
// Generated 19.Aðu.2013 17:08:30 by Hibernate Tools 3.4.0.CR1

/**
 * Sonuclar generated by hbm2java
 */
public class Sonuclar implements java.io.Serializable {

	private Integer sonucId;
	private Musteriler musteriler;
	private Integer oluDeri;
	private String ciltTipi;
	private Integer lekeAdet;
	private Integer lekeOrani;
	private Integer kirisiklik;
	private Integer ph;

	public Sonuclar() {
	}

	public Sonuclar(Musteriler musteriler, Integer oluDeri, String ciltTipi,
			Integer lekeAdet, Integer lekeOrani, Integer kirisiklik, Integer ph) {
		this.musteriler = musteriler;
		this.oluDeri = oluDeri;
		this.ciltTipi = ciltTipi;
		this.lekeAdet = lekeAdet;
		this.lekeOrani = lekeOrani;
		this.kirisiklik = kirisiklik;
		this.ph = ph;
	}

	public Integer getSonucId() {
		return this.sonucId;
	}

	public void setSonucId(Integer sonucId) {
		this.sonucId = sonucId;
	}

	public Musteriler getMusteriler() {
		return this.musteriler;
	}

	public void setMusteriler(Musteriler musteriler) {
		this.musteriler = musteriler;
	}

	public Integer getOluDeri() {
		return this.oluDeri;
	}

	public void setOluDeri(Integer oluDeri) {
		this.oluDeri = oluDeri;
	}

	public String getCiltTipi() {
		return this.ciltTipi;
	}

	public void setCiltTipi(String ciltTipi) {
		this.ciltTipi = ciltTipi;
	}

	public Integer getLekeAdet() {
		return this.lekeAdet;
	}

	public void setLekeAdet(Integer lekeAdet) {
		this.lekeAdet = lekeAdet;
	}

	public Integer getLekeOrani() {
		return this.lekeOrani;
	}

	public void setLekeOrani(Integer lekeOrani) {
		this.lekeOrani = lekeOrani;
	}

	public Integer getKirisiklik() {
		return this.kirisiklik;
	}

	public void setKirisiklik(Integer kirisiklik) {
		this.kirisiklik = kirisiklik;
	}

	public Integer getPh() {
		return this.ph;
	}

	public void setPh(Integer ph) {
		this.ph = ph;
	}

}
